[theme]
primaryColor="#006600" #user input box outline
backgroundColor="#FF9933" #Whole background
secondaryBackgroundColor="#66FF66" #user input box background
textColor="#000000" #Pokemon Insight and blurb
font="sans serif"


 